export type Resource = 'clients'|'properties'|'jobs'|'visits'|'quotes'|'invoices'|'payments';
export interface MirrorRecord { jobberId:string; fields:Record<string,unknown>; sourcePayload:Record<string,unknown>; sourceUpdatedAt:string|null }
export interface SyncResourceDefinition { resource:Resource; query:string; connectionKey:string; map(node:Record<string,any>):MirrorRecord }
const id=(node:Record<string,any>)=>String(node.id);
const scalar=(value:unknown): number|null => value == null ? null : Number(typeof value === 'object' && value && 'value' in value ? (value as any).value : value);
export const definitions: SyncResourceDefinition[] = [
 { resource:'clients', connectionKey:'clients', query:`query Clients($cursor:String){ clients(first:100,after:$cursor){ nodes{id name{first last full} companyName isArchived emails{primary address} phones{primary number} billingAddress{street1 street2 city province postalCode} updatedAt} pageInfo{hasNextPage endCursor} } }`, map:n=>({jobberId:id(n), fields:{name:n.name?.full??n.companyName??'Unnamed client',first_name:n.name?.first,last_name:n.name?.last,company_name:n.companyName,email:n.emails?.find?.((x:any)=>x.primary)?.address??n.emails?.[0]?.address,phone:n.phones?.find?.((x:any)=>x.primary)?.number??n.phones?.[0]?.number,is_active:!n.isArchived,billing_address:[n.billingAddress?.street1,n.billingAddress?.street2].filter(Boolean).join(', ')||null,city:n.billingAddress?.city,province:n.billingAddress?.province,postal_code:n.billingAddress?.postalCode,archived_at:n.isArchived?n.updatedAt:null},sourcePayload:n,sourceUpdatedAt:n.updatedAt??null})},
 { resource:'properties', connectionKey:'properties', query:`query Properties($cursor:String){ properties(first:100,after:$cursor){ nodes{id client{id} address{street1 street2 city province postalCode} isArchived updatedAt} pageInfo{hasNextPage endCursor} } }`, map:n=>({jobberId:id(n),fields:{client_jobber_id:n.client?.id,address:[n.address?.street1,n.address?.street2].filter(Boolean).join(', ')||null,city:n.address?.city,province:n.address?.province,postal_code:n.address?.postalCode,is_active:!n.isArchived},sourcePayload:n,sourceUpdatedAt:n.updatedAt??null})},
 { resource:'jobs', connectionKey:'jobs', query:`query Jobs($cursor:String){ jobs(first:100,after:$cursor){ nodes{id jobNumber title jobStatus startAt endAt completedAt client{id} property{id} updatedAt} pageInfo{hasNextPage endCursor} } }`, map:n=>({jobberId:id(n),fields:{client_jobber_id:n.client?.id,property_jobber_id:n.property?.id,job_number:n.jobNumber,title:n.title,status:n.jobStatus??'unknown',start_at:n.startAt,end_at:n.endAt,closed_at:n.completedAt},sourcePayload:n,sourceUpdatedAt:n.updatedAt??null})},
 { resource:'visits', connectionKey:'visits', query:`query Visits($cursor:String){ visits(first:100,after:$cursor){ nodes{id title visitStatus startAt endAt completedAt job{id} updatedAt} pageInfo{hasNextPage endCursor} } }`, map:n=>({jobberId:id(n),fields:{job_jobber_id:n.job?.id,title:n.title,status:n.visitStatus??'unknown',start_at:n.startAt,end_at:n.endAt,completed_at:n.completedAt},sourcePayload:n,sourceUpdatedAt:n.updatedAt??null})},
 { resource:'quotes', connectionKey:'quotes', query:`query Quotes($cursor:String){ quotes(first:100,after:$cursor){ nodes{id quoteNumber title quoteStatus amounts{total} createdAt sentAt approvedAt client{id} updatedAt} pageInfo{hasNextPage endCursor} } }`, map:n=>({jobberId:id(n),fields:{client_jobber_id:n.client?.id,quote_number:n.quoteNumber,title:n.title,status:n.quoteStatus??'unknown',total:scalar(n.amounts?.total),created_date:n.createdAt?.slice?.(0,10),sent_at:n.sentAt,approved_at:n.approvedAt},sourcePayload:n,sourceUpdatedAt:n.updatedAt??null})},
 { resource:'invoices', connectionKey:'invoices', query:`query Invoices($cursor:String){ invoices(first:100,after:$cursor){ nodes{id invoiceNumber subject invoiceStatus amounts{total outstanding} issuedDate dueDate paidAt client{id} updatedAt} pageInfo{hasNextPage endCursor} } }`, map:n=>({jobberId:id(n),fields:{client_jobber_id:n.client?.id,invoice_number:n.invoiceNumber,subject:n.subject,status:n.invoiceStatus??'unknown',total:scalar(n.amounts?.total)??0,balance:scalar(n.amounts?.outstanding)??0,issued_date:n.issuedDate,due_date:n.dueDate,paid_at:n.paidAt},sourcePayload:n,sourceUpdatedAt:n.updatedAt??null})},
 { resource:'payments', connectionKey:'payments', query:`query Payments($cursor:String){ payments(first:100,after:$cursor){ nodes{id amount paymentMethod createdAt client{id} invoice{id} updatedAt} pageInfo{hasNextPage endCursor} } }`, map:n=>({jobberId:id(n),fields:{client_jobber_id:n.client?.id,invoice_jobber_id:n.invoice?.id,amount:scalar(n.amount)??0,paid_at:n.createdAt,payment_method:n.paymentMethod},sourcePayload:n,sourceUpdatedAt:n.updatedAt??null})}
];
