import type { Queryable } from '../../../database/client.js';
export interface WebhookEvent {id:string;deliveryId:string;topic:string;externalItemId:string|null;payload:Record<string,unknown>;attemptCount:number}
export class WebhookEventStore{
 constructor(private db:Queryable){}
 async enqueue(input:{deliveryId:string;topic:string;externalAccountId?:string;externalItemId?:string;payload:Record<string,unknown>}):Promise<{id:string;duplicate:boolean}>{const r=await this.db.query(`INSERT INTO webhook_events(delivery_id,topic,external_account_id,external_item_id,payload) VALUES($1,$2,$3,$4,$5) ON CONFLICT(provider,delivery_id) DO NOTHING RETURNING id`,[input.deliveryId,input.topic,input.externalAccountId??null,input.externalItemId??null,JSON.stringify(input.payload)]);if(r.rows[0])return{id:String(r.rows[0].id),duplicate:false};const old=await this.db.query('SELECT id FROM webhook_events WHERE provider=$1 AND delivery_id=$2',['jobber',input.deliveryId]);return{id:String(old.rows[0].id),duplicate:true};}
 async claim():Promise<WebhookEvent|null>{const r=await this.db.query(`UPDATE webhook_events SET status='processing',processing_started_at=now(),attempt_count=attempt_count+1 WHERE id=(SELECT id FROM webhook_events WHERE status IN ('pending','failed') AND available_at<=now() AND attempt_count<8 ORDER BY received_at FOR UPDATE SKIP LOCKED LIMIT 1) RETURNING id,delivery_id,topic,external_item_id,payload,attempt_count`);const x=r.rows[0];return x?{id:String(x.id),deliveryId:x.delivery_id,topic:x.topic,externalItemId:x.external_item_id,payload:x.payload,attemptCount:x.attempt_count}:null;}
 async complete(id:string):Promise<void>{await this.db.query(`UPDATE webhook_events SET status='processed',processed_at=now(),last_error=NULL WHERE id=$1`,[id]);}
 async fail(event:WebhookEvent,error:string):Promise<void>{const terminal=event.attemptCount>=8;await this.db.query(`UPDATE webhook_events SET status=$2,last_error=$3,available_at=now()+(LEAST(300,power(2,$4)) * interval '1 second') WHERE id=$1`,[event.id,terminal?'failed':'pending',error.slice(0,1000),event.attemptCount]);}
}
